version: '3.8'

services:
  rstudio:
    build:
      context: ./rstudio
    container_name: rstudio
    volumes:
      - /share:/share
    environment:
      - PASSWORD=${PASSWORD}
      - ROOT=TRUE
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - rstudio
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
